### PR TITLE
DRAFT: try to remove code duplication for different datatypes using macro

### PR DESCRIPTION
**Pull request by evgenii-kuznetcov**
Didn't want to open macro pandora box but this makes code much shorter. IDE support in vscode still works. 
If we like the approach, I can add missing datatypes

### CODE REVIEW

**Comment by thobai** [comment]
It does make the code shorter, but actually, I find the `tdigest_cast` version more elegant. We have to cast anyways, so we can also do that beforehand. There's no performance impact from that. What do you think?

**Comment by evgenii-kuznetcov** [comment]
> It does make the code shorter, but actually, I find the `tdigest_cast` version more elegant. We have to cast anyways, so we can also do that beforehand. There's no performance impact from that. What do you think?

Agree, `tdigest_cast` should be better. Didn't notice this function and it was not used

**Comment by thobai** [comment]
ok, then we should make that one the default and actually remove the other one. But for that we also have to bring in the changes that you already did for the current function. Will you take this over or shall I do it sometime?

**Comment by evgenii-kuznetcov** [comment]
See https://github.com/appian/polars-tdigest/pull/13

**Pull request closed without merging**
